### ISSUE TITLE
When will you plan to release the data? 

### ISSUE THREAD

**Issue by plmsmile** [RifleZhang/LLaVA-Hound-DPO#1]
Thanks for the sharing of the great  Video-DPO work!!!

When will you plan to release the pretraining & finetuning & dpo data? (900k video caption, 240k video instruction and 17k preference data)

**Comment by RifleZhang** [comment]
Today: added DPO pipeline, including 300k caption and 17k preference data.
Will add SFT data, and the rest 600k caption used for pre-training.
