### ISSUE TITLE
How did you select activitynet video clip from scenedetect？

### ISSUE THREAD

**Issue by osttkm** [RifleZhang/LLaVA-Hound-DPO#11]
Hello,

I have a question regarding the data segmentation in ActivityNet. For example, when I use scenedetect to split the video file v_zyi4NVylqB0.mp4, it results in 32 segments. However, I noticed that in the video-caption-train.jsonl file, which contains the ActivityNet data, only three video clips are used: v_zyi4NVylqB0.mp4-Scene-001, v_zyi4NVylqB0.mp4-Scene-002, and v_zyi4NVylqB0.mp4-Scene-003.

Could you please explain the criteria used for selecting these specific video clips? Manually checking the correspondence between images is a very time-consuming task.

If there is an algorithm or code available, I would greatly appreciate it if you could share it with me.

Thank you for your assistance.

**Comment by RifleZhang** [comment]
Right. Thanks for pointing that out. We do have used a tool for truncating scenes for Webvid. Let us find the tool and update to you soon.

**Comment by RifleZhang** [comment]
The video clipping code is at:
https://github.com/RifleZhang/LLaVA-Hound-DPO/issues/6

You can use that to match the scenes in the caption data. The scenes are randomly sampled.

**Comment by osttkm** [comment]
Thank you for your prompt response. 

I reviewed the clip code, but it seems that this code does not have the function to clip the original video and randomly sample from it.

**Comment by RifleZhang** [comment]
I see what your mean. Do you mean the scenes can't be matched? like scene-001 to the first one in the scene_list. 
We selected a subset for labeling from scene_list. Let us know if the scenes can't be matched, and we will try to figure out the original mapping.

**Comment by osttkm** [comment]
That's correct. In fact, when I attempted to split the original ActivityNet videos, it was difficult to identify the subsets as described in the actual JSON file. I tried to identify the subsets using metrics like SSIM with the split ActivityNet videos by utilizing the decode2frame function you shared, but it was not entirely successful.

I apologize for the inconvenience, but could you please share the mapping between the indices of the original data when it was split and the sub-scenes specified in the JSON file for the ActivityNet data in the video_caption_pretrain.jsonl file shared on Hugging Face?

**Comment by RifleZhang** [comment]
I understand the issue. Let us figure out a solution and get back to you soon.

**Comment by RifleZhang** [comment]
Hello,
We have checked our code and found that we relabeled the scenes after sampling. However, the mapping from original clips to the new label was not recoverable. 
I am wondering if any automated approach, such as pixel-wise  loss (i.e. MSE) could do the mapping. I think SSIM leverages correlation and may not be suitable for this mapping.
Thanks!

**Comment by osttkm** [comment]
Thank you for working on the data recovery. 
It's unfortunate that the recovery wasn't successful, but I will try to experiment further based on your advice！
