### ISSUE TITLE
Source of raw video

### ISSUE THREAD

**Issue by exiawsh** [RifleZhang/LLaVA-Hound-DPO#12]
Hi, is it possible to opensource the raw video (just the path in the original dataset, **e.g. Activity/v_Z_1Zoc6lINU_5.mp4, timestamp:[ "00:00:00.000", "00:00:10.000" ]** ) with the corresponding timestamp for the training video? 
Because I want to embed different frame rate in the model.

**Comment by RifleZhang** [comment]
Hello, 
Thanks for your suggestions! I don't have access to the server right now. Let me sync with my collaborators to check if it is possible.

**Comment by exiawsh** [comment]
> Hello, Thanks for your suggestions! I don't have access to the server right now. Let me sync with my collaborators to check if it is possible.

Thanks，it's really kind of you.

**Comment by exiawsh** [comment]
@RifleZhang Hello~ Any update on this issue. Just data source and timestamp is fine.

**Comment by tyleryzhu** [comment]
@RifleZhang @exiawsh also following this, would be a great help!

**Comment by RifleZhang** [comment]
Sorry for the delay, your requested raw data for activitynet is here: 
https://huggingface.co/datasets/ShareGPTVideo/train_raw_video
