### ISSUE TITLE
Would you share the inference results, since `gpt-3.5-turbo-0301` will be deprecated this year?

### ISSUE THREAD

**Issue by SCZwangxiao** [RifleZhang/LLaVA-Hound-DPO#2]
I really appreciate your work on ShareGPTVideo and DPO for videoLLM. Moreover, I think maybe sharing the inference results would help us better follow your works?

As you said in the paper, the revaluation varies dramatically between GPT versions. In my experiments, the accuracy diff between `0301` and `1106` is usually larger than 10%.  Unfortunately, the openAI's website says that the earlier versions (<= `0613`) will be deprecated in [June 13, 2024](https://platform.openai.com/docs/models/gpt-3-5-turbo).

**Comment by guilk** [comment]
Thanks a lot for your suggestion. We will upload our predictions for different model variants.

**Comment by RifleZhang** [comment]
Inference and gpt eval results are pushed to https://huggingface.co/datasets/ShareGPTVideo/test_video_and_instruction/blob/main/compile_test_result.tar.gz
