### ISSUE TITLE
video frame rate

### ISSUE THREAD

**Issue by wenhaochai** [RifleZhang/LLaVA-Hound-DPO#3]
thanks your great data contribution! I'm wondering the frame fate of your extracted video? Thanks!

**Comment by guilk** [comment]
Hi, we use `ffmpeg -loglevel quiet -i VIDEO_PATH -vf "scale=336:-1,fps=2" FRAME_ROOT` for video decoding. Then we use `np.linspace(0, duration-1, num_segments, dtype=int) ` to uniformly sample frames.

**Comment by wenhaochai** [comment]
sounds good! so the image seq in each folder are under fps=2 right @guilk 
and i found extremely slow when unzip each tar.gz file, is that normal?

**Comment by wenhaochai** [comment]
also notice that there is no chunk 22 in 600k 👁️

**Comment by wenhaochai** [comment]
and 29 also missing

**Comment by RifleZhang** [comment]
> sounds good! so the image seq in each folder are under fps=2 right @guilk and i found extremely slow when unzip each tar.gz file, is that normal?

In the inference example in README, the video to frame function we used is defined in inference.inference_utils.decode2frame

We just loaded the missing chunks and fixed a typo in setup_train_data.sh. Let me know if you run into any problems. As for the speed, it probably takes about 5-10 mins to unzip everything.

**Comment by wenhaochai** [comment]
thx your fix (your typo make my /home messy lol)
